# Task CR Definition
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ignitors.sirocco.cloud
spec:
  group: sirocco.cloud
  version: v1alpha1
  scope: Namespaced
  names:
    kind: Ignitor
    shortNames:
      - ig
    plural: ignitors
    singular: ignitor
  additionalPrinterColumns:
    - name: scheduled
      type: string
      description: When the ignitor is going to be triggered
      JSONPath: .spec.scheduled
