# Task1
---
apiVersion: sirocco.cloud/v1alpha1
kind: Task
metadata:
  name: task1
  labels:
    app: test1
spec:
  description: This task should return true after 10 sec.
  startOnIgnition:
    - ignitor1
  startOnSuccess:
  startOnFailure:
  successActions:
  failureActions:
    - SIROCCO-DEMO-ALERT-FAILURE
  template:
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "sleep(2); open(F, '>/dev/termination-log'); print F 'DATA'; close F;"]
      restartPolicy: Never