/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	scheme "orcaoperator/pkg/clients/clientset/versioned/scheme"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "orcaoperator/pkg/apis/sirocco.cloud/v1alpha1"
)

// IgnitorsGetter has a method to return a IgnitorInterface.
// A group's client should implement this interface.
type IgnitorsGetter interface {
	Ignitors(namespace string) IgnitorInterface
}

// IgnitorInterface has methods to work with Ignitor resources.
type IgnitorInterface interface {
	Create(*v1alpha1.Ignitor) (*v1alpha1.Ignitor, error)
	Update(*v1alpha1.Ignitor) (*v1alpha1.Ignitor, error)
	UpdateStatus(*v1alpha1.Ignitor) (*v1alpha1.Ignitor, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.Ignitor, error)
	List(opts v1.ListOptions) (*v1alpha1.IgnitorList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Ignitor, err error)
	IgnitorExpansion
}

// ignitors implements IgnitorInterface
type ignitors struct {
	client rest.Interface
	ns     string
}

// newIgnitors returns a Ignitors
func newIgnitors(c *SiroccoV1alpha1Client, namespace string) *ignitors {
	return &ignitors{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the ignitor, and returns the corresponding ignitor object, and an error if there is any.
func (c *ignitors) Get(name string, options v1.GetOptions) (result *v1alpha1.Ignitor, err error) {
	result = &v1alpha1.Ignitor{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("ignitors").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Ignitors that match those selectors.
func (c *ignitors) List(opts v1.ListOptions) (result *v1alpha1.IgnitorList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.IgnitorList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("ignitors").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested ignitors.
func (c *ignitors) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("ignitors").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a ignitor and creates it.  Returns the server's representation of the ignitor, and an error, if there is any.
func (c *ignitors) Create(ignitor *v1alpha1.Ignitor) (result *v1alpha1.Ignitor, err error) {
	result = &v1alpha1.Ignitor{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("ignitors").
		Body(ignitor).
		Do().
		Into(result)
	return
}

// Update takes the representation of a ignitor and updates it. Returns the server's representation of the ignitor, and an error, if there is any.
func (c *ignitors) Update(ignitor *v1alpha1.Ignitor) (result *v1alpha1.Ignitor, err error) {
	result = &v1alpha1.Ignitor{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("ignitors").
		Name(ignitor.Name).
		Body(ignitor).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *ignitors) UpdateStatus(ignitor *v1alpha1.Ignitor) (result *v1alpha1.Ignitor, err error) {
	result = &v1alpha1.Ignitor{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("ignitors").
		Name(ignitor.Name).
		SubResource("status").
		Body(ignitor).
		Do().
		Into(result)
	return
}

// Delete takes name of the ignitor and deletes it. Returns an error if one occurs.
func (c *ignitors) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("ignitors").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *ignitors) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("ignitors").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched ignitor.
func (c *ignitors) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Ignitor, err error) {
	result = &v1alpha1.Ignitor{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("ignitors").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
