/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	versioned "orcaoperator/pkg/clients/clientset/versioned"
	internalinterfaces "orcaoperator/pkg/clients/informers/externalversions/internalinterfaces"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	siroccocloudv1alpha1 "orcaoperator/pkg/apis/sirocco.cloud/v1alpha1"
	v1alpha1 "orcaoperator/pkg/clients/listers/sirocco.cloud/v1alpha1"
)

// IgnitorInformer provides access to a shared informer and lister for
// Ignitors.
type IgnitorInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.IgnitorLister
}

type ignitorInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewIgnitorInformer constructs a new informer for Ignitor type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewIgnitorInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredIgnitorInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredIgnitorInformer constructs a new informer for Ignitor type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredIgnitorInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SiroccoV1alpha1().Ignitors(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SiroccoV1alpha1().Ignitors(namespace).Watch(options)
			},
		},
		&siroccocloudv1alpha1.Ignitor{},
		resyncPeriod,
		indexers,
	)
}

func (f *ignitorInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredIgnitorInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *ignitorInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&siroccocloudv1alpha1.Ignitor{}, f.defaultInformer)
}

func (f *ignitorInformer) Lister() v1alpha1.IgnitorLister {
	return v1alpha1.NewIgnitorLister(f.Informer().GetIndexer())
}
