/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "orcaoperator/pkg/apis/orca/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeIgnitors implements IgnitorInterface
type FakeIgnitors struct {
	Fake *FakeSiroccoV1alpha1
	ns   string
}

var ignitorsResource = schema.GroupVersionResource{Group: "sirocco.cloud", Version: "v1alpha1", Resource: "ignitors"}

var ignitorsKind = schema.GroupVersionKind{Group: "sirocco.cloud", Version: "v1alpha1", Kind: "Ignitor"}

// Get takes name of the ignitor, and returns the corresponding ignitor object, and an error if there is any.
func (c *FakeIgnitors) Get(name string, options v1.GetOptions) (result *v1alpha1.Ignitor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(ignitorsResource, c.ns, name), &v1alpha1.Ignitor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Ignitor), err
}

// List takes label and field selectors, and returns the list of Ignitors that match those selectors.
func (c *FakeIgnitors) List(opts v1.ListOptions) (result *v1alpha1.IgnitorList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(ignitorsResource, ignitorsKind, c.ns, opts), &v1alpha1.IgnitorList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.IgnitorList{ListMeta: obj.(*v1alpha1.IgnitorList).ListMeta}
	for _, item := range obj.(*v1alpha1.IgnitorList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested ignitors.
func (c *FakeIgnitors) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(ignitorsResource, c.ns, opts))

}

// Create takes the representation of a ignitor and creates it.  Returns the server's representation of the ignitor, and an error, if there is any.
func (c *FakeIgnitors) Create(ignitor *v1alpha1.Ignitor) (result *v1alpha1.Ignitor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(ignitorsResource, c.ns, ignitor), &v1alpha1.Ignitor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Ignitor), err
}

// Update takes the representation of a ignitor and updates it. Returns the server's representation of the ignitor, and an error, if there is any.
func (c *FakeIgnitors) Update(ignitor *v1alpha1.Ignitor) (result *v1alpha1.Ignitor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(ignitorsResource, c.ns, ignitor), &v1alpha1.Ignitor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Ignitor), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeIgnitors) UpdateStatus(ignitor *v1alpha1.Ignitor) (*v1alpha1.Ignitor, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(ignitorsResource, "status", c.ns, ignitor), &v1alpha1.Ignitor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Ignitor), err
}

// Delete takes name of the ignitor and deletes it. Returns an error if one occurs.
func (c *FakeIgnitors) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(ignitorsResource, c.ns, name), &v1alpha1.Ignitor{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeIgnitors) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(ignitorsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.IgnitorList{})
	return err
}

// Patch applies the patch and returns the patched ignitor.
func (c *FakeIgnitors) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Ignitor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(ignitorsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Ignitor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Ignitor), err
}
